# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0-LNIi7sFsFq8Qf2yQAFRCSF31zQXxs

#import
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df=pd.read_csv(r"world_happiness_2026 (3).csv")
df

"""#describe"""

df.tail(10)

df.head(10)

df.describe()

df.info()

df.pivot_table(index=['region'],values='rank',aggfunc='mean').sort_values('rank',ascending=False)

df.pivot_table(index=['region'],values='score',aggfunc='mean').sort_values('score',ascending=False)

cols = ['score'	,'gdp_per_capita',	'social_support',	'healthy_life_expectancy',	'freedom',	'generosity',	'corruption']

result = {}

for col in cols:
    highest = df.loc[df[col].idxmax(), 'country']
    lowest = df.loc[df[col].idxmin(), 'country']

    result[col] = {
        'highest': highest,
        'lowest': lowest
    }

result
summary = pd.DataFrame({
    'highest_country': [df.loc[df[col].idxmax(), 'country'] for col in cols],
    'lowest_country': [df.loc[df[col].idxmin(), 'country'] for col in cols]
}, index=cols)

summary

lowest = df.loc[df['rank'].idxmin()]
highest = df.loc[df['rank'].idxmax()]
resulte=pd.concat([lowest, highest], axis=1)
resulte

sns.lineplot(data=df ,x='rank' ,y='score')
plt.show()

sns.boxenplot(data=df,x="region",y="rank")
plt.xticks(rotation=75)
plt.show()

corr=df.corr(numeric_only=True)
sns.heatmap(corr,annot=True,cmap="coolwarm")
plt.show()

sns.pairplot(data=df)
plt.show()